server:
  port: 8089

spring:
  mvc:
  # 配置静态资源映射路径，/public、/resources路径失效
  #static-path-pattern: /static/**
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.13.11;DatabaseName=GrainSuperVisionDataUpload_20201230_test
    username: grainer
    password: password
    initialSize: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  # 引擎模板配置
  thymeleaf:
    cache: false # 关闭缓存
    mode: LEGACYHTML5 # 去除htm5严格校验
    prefix: classpath:/templates/ # 指定 thymeleaf 模板路径
    encoding: UTF-8 # 指定字符集编码

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.js.aisino.repository.entity

logging:
  config: classpath:logback-boot.xml


cron1: '0 */1 * * * ?'
